export const DEFAULT_ELO_RATING = 1500;
export const DEFAULT_ELO_K_FACTOR = 32;
export const DEFAULT_SURGEON_PRIOR_COMPARISONS = 10;
export const DEFAULT_COMMUNITY_SCORE_CENTER = 50;
export const DEFAULT_RATING_POINTS_PER_COMMUNITY_POINT = 8;
export const DEFAULT_MIN_RATED_CASES = 3;
export const DEFAULT_MIN_SURGEON_COMPARISONS = 10;
